import cv2
import cv2.aruco as aruco
import os

# --- PENGATURAN PATH DATA ---
# Menyimpan file kalibrasi di folder 'data' agar rapi
DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)

CAMERA_DATA_PATH = os.path.join(DATA_DIR, "data_kamera.npz")
LASER_DATA_PATH = os.path.join(DATA_DIR, "data_laser.npz")

# Path to the extrinsic calibration file generated by debug_extrinsics.py (in Root)
# Root is up 2 levels from here (core -> NetraScan-Lite -> Root) if running from app.py
# But __file__ is inside core.
# .../Root/NetraScan-Lite/core/config.py
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
EXTRINSIC_DATA_PATH = os.path.join(PROJECT_ROOT, "calibration.json")

# --- PENGATURAN PAPAN CHARUCO ---
# Ganti angka ini sesuai hasil pengukuran penggaris Anda (dalam meter)
# Target: 12.5cm x 12.5cm (5x5 grid)
SQUARE_LENGTH = 0.025  # 2.5 cm
MARKER_LENGTH = 0.018  # 1.8 cm

# Dictionary ArUco (Harus sama dengan yang di-generate)
ARUCO_DICT = aruco.getPredefinedDictionary(aruco.DICT_6X6_250)
BOARD_SIZE = (5, 5) # Jumlah kotak (lebar x tinggi)

# --- PENGATURAN CHECKERBOARD BIASA (untuk kalibrasi Z axis) ---
CHECKER_BOARD_SIZE = (4, 4)     # Inner corners (4x4 for 5x5 squares)
CHECKER_SQUARE_SIZE = 0.025     # 25mm in meters

# --- PENGATURAN KAMERA ---
CAMERA_INDEX = 1  # Default 1 (External), Fallback 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

# --- PENGATURAN LASER (CHANNEL DIFFERENCE) ---
# Ambang batas deteksi laser (0-255)
# Naikkan jika lampu ruangan terlalu terang
LASER_THRESHOLD = 30

# --- PENGATURAN MEJA PUTAR ---
# Total langkah untuk 1 putaran penuh (360 derajat)
# NEMA 17 (200 step) x 8 microstep = 1600 step per rev stepper
# Gear ratio: Turntable gear 20cm / Stepper gear 7cm = 20/7 ≈ 2.857
# Steps per turntable rev = 1600 × (20/7) ≈ 4571
TURNTABLE_STEPS_PER_REV = 4571

# --- PENGATURAN PERGERAKAN SCAN (RESOLUTION) ---
# Jumlah langkah scanning dalam 1 putaran penuh.
# 360 = 1 derajat per langkah (Detail Standar)
# 720 = 0.5 derajat per langkah (Lebih Halus, Lebih Lama)
# 180 = 2 derajat per langkah (Cepat, Kurang Detail)
SCAN_STEPS_TOTAL = 4  # DEBUG: 4 step (0°, 90°, 180°, 270°)

# Waktu jeda (detik) setiap kali meja berhenti sebelum ambil foto.
# Jika hasil scan berbayang/goyang, naikkan jadi 0.5 atau 1.0.
SCAN_SETTLE_TIME = 0.15

# --- PENGATURAN OFFSET HASIL SCAN ---
# Tambahkan nilai ini (dalam meter/satuan sistem) ke posisi akhir.
# X: Kanan(+) / Kiri(-)
# Y: Atas(+) / Bawah(-) (Tergantung Axis Map)
# Z: Depan(+) / Belakang(-)
SCAN_X_OFFSET = 0.0
SCAN_Y_OFFSET = 0.0
SCAN_Z_OFFSET = 0.0

# Tambahkan nilai ini (dalam derajat) untuk memutar hasil scan.
# Format: [Rotasi X, Rotasi Y, Rotasi Z]
# Contoh: [5.0, 0.0, 0.0] -> Miring 5 derajat di sumbu X.
SCAN_ROTATION_OFFSET = [180.0, 0.0, 0.0]

# --- INVERT ROTATION (OLD - IGNORE IF USING AXIS MAP BELOW) ---
# Set True jika hasil scan terbalik (mirrored) depan-belakang/kiri-kanan
INVERT_ROTATION = True

# --- EXTREME POV CONTROL (MANUAL AXIS MAPPING) ---
# Gunakan ini untuk mengatur ulang sumbu X, Y, Z sesuka hati.
# Format: [Index Source X, Index Source Y, Index Source Z]
# 0 = X Asli (Kanan/Kiri)
# 1 = Y Asli (Atas/Bawah)
# 2 = Z Asli (Depan/Belakang)

# Contoh 1 (Default): [0, 1, 2] -> X=X, Y=Y, Z=Z
# Contoh 2 (Tukar Y dan Z): [0, 2, 1] -> X=X, Y=Z (Tinggi jadi Depan), Z=Y (Depan jadi Tinggi)
POINT_CLOUD_AXIS_MAP = [0, 1, 2]

# Invert Sumbu (1 = Normal, -1 = Balik Arah)
# Format: [Invert X, Invert Y, Invert Z]
# Invert Sumbu (1 = Normal, -1 = Balik Arah)
# Format: [Invert X, Invert Y, Invert Z]
POINT_CLOUD_AXIS_INVERT = [1, 1, 1]

# --- VISUALIZER SETTINGS (FRONTEND) ---
# Posisi Awal Kamera di Web Visualizer [X, Y, Z]
# Ubah ini jika ingin tampilan awal dari sudut lain.
VISUALIZER_CAMERA_POSITION = [5, 5, 5]
